### ISSUE TITLE
Determinant tries to access the record entry "matrix" of a sparse matrix over an internal ring

### ISSUE THREAD

**Issue by martin-leuner** [homalg-project/MatricesForHomalg#11]
This seems to be a shared issue between Matrices and Gauss. Matrices' Determinant method does not check whether its argument is a dense matrix. Gauss does not implement Determinant at all.

gap> m := HomalgMatrix( [[1]], HomalgFieldOfRationals() );
gap> Determinant( m );
Error, Record: '<rec>.matrix' must have an assigned value in
  return Determinant( Eval( C )!.matrix ); called from
DeterminantMat( C )
brk> IsIdenticalObj(C,m);
true
brk> InfoOfObject( Eval( C ) );
rec( attributes := rec(  ), components := rec( entries := [ [ 1 ] ], indices := [ [ 1 ] ], ncols := 1, nrows := 1, ring := Rationals ), object := <a 1 x 1 sparse matrix over Rationals>, properties := rec(  ) )

**Comment by mohamed-barakat** [comment]
This patch will negatively affect the performance of internal dense matrices. I would accept a separate fallback method for sparse matrices.
