### ISSUE TITLE
Slow LIMAT/COLEM?

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/MatricesForHomalg#12]
The following example indicates that the LIMAT/COLEM methods might be slowing down the computations:
```
LoadPackage( "GradedRingForHomalg" );
S := GradedRing( HomalgFieldOfRationalsInDefaultCAS( ) * "x,y,z" );
LoadPackage( "GradedModules" );
I := GradedLeftSubmodule( "x", S ) * MaximalGradedLeftIdeal( S )
     + GradedLeftSubmodule( "y^3", S );
M := FactorObject( I );
homalgIOMode( "D" );
FilteredByPurity( M );
```

**Comment by mohamed-barakat** [comment]
@sebasguts: I am now sure that the bottleneck are the TODO-lists! You can interrupt it during the slow logic and you will end up being in the middle of the TODO-lists code.

**Comment by sebasguts** [comment]
New patch for ToDoLists should make it faster again :). At least first tests show this. Please look at https://github.com/homalg-project/ToolsForHomalg/commit/955d0e5311d2ae7c64cd2370ba53405e53e7fe6a

**Comment by mohamed-barakat** [comment]
:+1:
